export enum productAction{
  SEARCH_DATA = "SEARCH_DATA",
  DISPLAY_DATA = "DISPLAY_DATA",
  SHOW_ORDER = "SHOW_ORDER",
  SHOW_CART = "SHOW_CART",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  TOTAL_CART_COST = "TOTAL_CART_COST",
  TOTAL_ORDER_COST = "TOTAL_ORDER_COST",
  RESET_TOTAL_COST = "RESET_TOTAL_COST",
  PAYMENT = "PAYMENT"
}