export const LOGIN: string = "/login"
export const DASHBOARD: string = "/dashboard"
export const EMPLOYEE: string = "/employee"
export const AUTH: string = "/auth/authenticate"
export const EMPLOYEE_LOOKUP_MENU: string = "Employee Lookup"
export const DASHBOARD_MENU:string = "Dashboard"
export const LOGOUT: string = "Logout"
